project_name: sample-mcp

before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  - id: sample-mcp
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    files:
      - src: config.yml.sample
        dst: config.yaml
      - README.md